"""
Trace the supplied Olvable artwork into SVG paths.

  python brand/trace.py

Inputs:  brand/source/olvable-logo.png      (wordmark, black on transparent)
         brand/source/olvable-moodboard.png (the "va" secondary mark, crop)
Outputs: brand/wordmark.svg, brand/mark-va.svg, brand/paths.json,
         lib/brand-paths.ts, app/icon.svg, app/favicon.ico, app/apple-icon.png

Needs: pip install potracer pillow numpy. Note potracer's polarity is
inverted (False = ink), hence the ~mask.
"""
import json, os
from PIL import Image, ImageDraw, ImageFilter
import numpy as np, potrace

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
B = lambda *p: os.path.join(ROOT, 'brand', *p)
INK = (18, 19, 26, 255)

def trace(ink, opt=0.3, nd=1, turd=4):
    ys, xs = np.where(ink); m = ink[ys.min():ys.max()+1, xs.min():xs.max()+1]
    path = potrace.Bitmap(~m).trace(turdsize=turd, alphamax=1.0, opttolerance=opt)
    f = (lambda v: f"{v:.{nd}f}".rstrip('0').rstrip('.')) if nd else (lambda v: f"{v:.0f}")
    parts = []
    for c in path:
        s = c.start_point; d = [f"M{f(s.x)} {f(s.y)}"]
        for seg in c:
            if seg.is_corner: d.append(f"L{f(seg.c.x)} {f(seg.c.y)}L{f(seg.end_point.x)} {f(seg.end_point.y)}")
            else: d.append(f"C{f(seg.c1.x)} {f(seg.c1.y)} {f(seg.c2.x)} {f(seg.c2.y)} {f(seg.end_point.x)} {f(seg.end_point.y)}")
        d.append("Z"); parts.append("".join(d))
    return "".join(parts), int(m.shape[1]), int(m.shape[0]), m

def svg(d, w, h):
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {w} {h}" role="img" aria-label="Olvable"><path fill="currentColor" fill-rule="evenodd" d="{d}"/></svg>\n'

logo = np.array(Image.open(B('source', 'olvable-logo.png')).convert('RGBA'))[:, :, 3] > 128
wd, ww, wh, _ = trace(logo, 0.3, 0)
mb = np.array(Image.open(B('source', 'olvable-moodboard.png')).convert('L'))
vd, vw, vh, vmask = trace(mb[480:680, 190:580] > 128, 0.3, 1, 2)

open(B('wordmark.svg'), 'w').write(svg(wd, ww, wh))
open(B('mark-va.svg'), 'w').write(svg(vd, vw, vh))
open(B('mark-va-on-dark.svg'), 'w').write(f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {vw} {vh}"><path d="{vd}" fill="#F5F6FA" fill-rule="evenodd"/></svg>\n')
json.dump({'wordmark': {'w': ww, 'h': wh, 'd': wd}, 'va': {'w': vw, 'h': vh, 'd': vd}}, open(B('paths.json'), 'w'))
open(os.path.join(ROOT, 'lib', 'brand-paths.ts'), 'w').write(
    "/**\n * Olvable brand paths, traced from the supplied artwork (brand/source/).\n * Generated by brand/trace.py -- do not hand-edit. Fill with currentColor.\n */\n"
    f"export const WORDMARK = {{ w: {ww}, h: {wh}, d: '{wd}' }} as const\n"
    f"export const VA = {{ w: {vw}, h: {vh}, d: '{vd}' }} as const\n")

# App icon SVG: va in white on an ink rounded square.
gw = 82; gh = gw * vh / vw; sc = gw / vw
icon = (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128">\n  <rect width="128" height="128" rx="32" fill="#12131A"/>\n'
        f'  <g transform="translate({(128-gw)/2:.2f} {(128-gh)/2:.2f}) scale({sc:.5f})"><path d="{vd}" fill="#FFFFFF" fill-rule="evenodd"/></g>\n</svg>\n')
for p in (os.path.join(ROOT, 'app', 'icon.svg'), os.path.join(ROOT, 'app', 'favicon-src.svg'), B('app-icon.svg')):
    open(p, 'w').write(icon)

# Raster icons (favicon.ico, apple-icon.png) from the mask, supersampled.
def tile(size):
    S = size * 4
    im = Image.new('RGBA', (S, S), (0, 0, 0, 0))
    ImageDraw.Draw(im).rounded_rectangle([0, 0, S - 1, S - 1], radius=S // 4, fill=INK)
    gw_ = int(S * 0.64); gh_ = int(gw_ * vh / vw)
    g = Image.fromarray((vmask * 255).astype('uint8')).resize((gw_, gh_), Image.LANCZOS).filter(ImageFilter.GaussianBlur(0.6))
    white = Image.new('RGBA', g.size, (255, 255, 255, 255))
    im.paste(white, ((S - gw_) // 2, (S - gh_) // 2), g)
    return im.resize((size, size), Image.LANCZOS)
tile(180).save(os.path.join(ROOT, 'app', 'apple-icon.png'))
tile(512).save(B('app-icon-512.png'))
tile(64).save(os.path.join(ROOT, 'app', 'favicon.ico'), sizes=[(16, 16), (32, 32), (48, 48), (64, 64)])
print('traced: wordmark', ww, wh, len(wd), 'bytes; va', vw, vh, len(vd), 'bytes; icons written')
