// DEMO_MODE=static: the whole read path served from bundled seed data,
// generated by seed/generate.mjs from the same source as seed.sql.
import type {
  EventRow,
  ProfileWithSkills,
  ProjectDetail,
  ProjectRow,
  RequirementRow,
} from "@/lib/types";
import seed from "./static-seed.json";

type SeedProject = ProjectRow & {
  requirements: RequirementRow[];
  member_ids: string[];
};

const profiles = seed.profiles as unknown as ProfileWithSkills[];
const events = seed.events as unknown as EventRow[];
const projects = seed.projects as unknown as SeedProject[];

function detail(p: SeedProject): ProjectDetail {
  return {
    ...p,
    members: profiles.filter((m) => p.member_ids.includes(m.id)),
    event: events.find((e) => e.id === p.event_id) ?? null,
  };
}

export const staticRepo = {
  pool: (): ProfileWithSkills[] => profiles,
  events: (): EventRow[] => events,
  event: (id: string): EventRow | null => events.find((e) => e.id === id) ?? null,
  projects: (): ProjectDetail[] => projects.map(detail),
  project: (id: string): ProjectDetail | null => {
    const p = projects.find((x) => x.id === id);
    return p ? detail(p) : null;
  },
  profileByHandle: (handle: string): ProfileWithSkills | null =>
    profiles.find((p) => p.handle === handle) ?? null,
};
